name: Build and Publish Multi-Arch Docker Image to GHCR

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU (for cross-platform build)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/dem0nic69/stepdaddylivehd:latest,ghcr.io/dem0nic69/stepdaddylivehd:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
